spring:
  application:
    name: school-label
server:
  port: 8799
  servlet:
    context-path: /school/label
mybatis-plus:
  # 如果是放在src/main/java目录下 classpath:/com/yourPackage/*/mapper/*Mapper.xml
  # 如果是放在resource目录 classpath:/mapper/*Mapper.xml (推荐)
  mapper-locations: classpath:/mybatis/mapper/*
  #  # 实体扫描，多个package用逗号或者分号分隔
  type-aliases-package: cn.zyforget.school.label.entity
  configuration:
    #    # 配置返回数据库(column下划线命名&&返回java实体是驼峰命名)，自动匹配无需as（没开启这个，SQL需要写as： select user_id as userId）
    map-underscore-to-camel-case: true
#    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    # 刷新mapper 调试神器
    refresh: true
    db-config:
      # 主键类型  auto:"数据库ID自增", input:"用户输入ID",id_worker:"全局唯一ID (数字类型唯一ID)"
      # id_worker_str:"全局唯一ID (字符串类型唯一ID)" uuid:"全局唯一ID UUID";
      id-type: auto
      # 字段策略 ignored:"忽略判断", not_null:"非 NULL 判断"), not_empty:"非空判断"
      field-strategy: not_null
      # 逻辑删除的字段需要注解  @TableLogic
      # 逻辑删除全局值
      logic-delete-value: 1 # 逻辑已删除值(默认为 1)
      logic-not-delete-value: 0 # 逻辑未删除值(默认为 0)
logging:
  level:
    cn:
      zyforget:
        school:
          label:
            mapper: DEBUG

